accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^alterar-dados/$', views.update_user, name='update_user'),
	url(r'^alterar-senha/$', views.update_password, name='update_password'),
	url(r'^atualizar/$', views.register, name='register'),
	#url(r'^meus-pedidos/$', include('checkout.urls', namespace='checkout'))

]

catalogo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',  views.product_list, name='product_list'),
	url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'), #[\w_-] qualquer caractere com _ ou -
	url(r'^produto/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem, name='create_cartitem'),
	url(r'^carrinho/$', views.cart_item, name='cart_item'),
	url(r'^finalizando/$', views.checkout, name='checkout'),
	url(r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view, name='pagseguro_view'),
	url(r'^meus-pedidos/$', views.order_list, name='order_list'),
	url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
	url(r'^notificacoes/pagseguro/$', views.pagseguro_notification, name='pagseguro_notification'),
	url(r'^finalizando/(?P<pk>\d+)/paypal/$', views.paypal_view,name='paypal_view'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from sitio import views
from catalogo import views as views_catalogo
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^catalogo/', include('catalogo.urls', namespace='catalogo')), #pagina de listagem dos produtos na app de catalogo
    url(r'^contato/$', views.contact, name='contact'), #pagina de listagem dos produtos na app de catalogo
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls), 
]

catalogo/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
	#code = models.IntegerField(primary_key=True) #Caso eu queira que o admin digite o id da categoria
	name = models.CharField('Nome', max_length=100)
	slug = models.SlugField('ID', max_length=100) #CharField para passagem na url (url amigavel)

	#Pegar a data em que o modelo é criado !!
	created = models.DateTimeField('Criado em', auto_now_add=True)
	#Pegar a data em que o modelo é salvo (ultima modificacao)
	modified = models.DateTimeField('Modificado em', auto_now=True)

	class Meta:
		verbose_name = 'Categoria'
		verbose_name_plural = 'Categorias'
		ordering = ['name'] #ordenando em ordem crescente pelos nomes

	def __str__(self):
		return self.name #apenas para aparecer o nome da classe na pagina admin

	def get_absolute_url(self):
		return reverse('catalogo:category', kwargs={'slug': self.slug})

class Product(models.Model):
	name = models.CharField('Nome', max_length=100)
	slug = models.SlugField('ID', max_length=100) #CharField
	category = models.ForeignKey('catalogo.Category', verbose_name='Categoria') #Chave estrangeira
	description = models.TextField('Descrição', blank=True) #blank true, ou seja, campo nao obrigatorio
	price = models.DecimalField('Preço', decimal_places=2, max_digits=8) #preços com no maximo 2 casas decimais

	#Pegar a data em que o modelo é criado !!
	created = models.DateTimeField('Criado em', auto_now_add=True)
	#Pegar a data em que o modelo é salvo (ultima modificacao)
	modified = models.DateTimeField('Modificado em', auto_now=True)

	class Meta:
		verbose_name = 'Produto'
		verbose_name_plural = 'Produtos'
		ordering = ['name'] #ordenando em ordem crescente pelos nomes

	def get_absolute_url(self):
		return reverse('catalogo:product', kwargs={'slug': self.slug})

catalogo/views.py
from django.shortcuts import render, get_object_or_404	
from .models import Category, Product
from django.views import generic
from django.views.generic import View, ListView

#Classe based on view. o ListView já é oferecido pelo django !!
class ProductListView(generic.ListView):
	model = Product
	template_name = 'catalogo/product_list.html'
	paginate_by = 3 #sistema de paginação do django (caso você queira ter mais páginas para listagem de algo)
					#Nesse caso, existiriam apenas 3 produtos por página!

#Função para impressão de produtos
#def product_list(request):
#	context = {
#		'products': Product.objects.all()
#	}
#	return render(request, 'catalogo/product_list.html', context)

#def category(request,slug):
#	category = Category.objects.get(slug=slug)
#	context = {
#		'current_category': category,
#		'product_list': Product.objects.filter(category=category),
#	}
#	return render(request, 'catalogo/category.html', context)

class CategoryListView(generic.ListView):
	def get_queryset(self):
		#Maneira de puxar o modelo com o slug pela url
		return Product.objects.filter(category__slug=self.kwargs['slug'])

	#Função para carregar a variável current_category (nome da categoria para template)
	def get_context_data(self, **kwargs):
		context = super(CategoryListView, self).get_context_data(**kwargs)
		context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
		return context

	template_name = 'catalogo/category.html'
	paginate_by = 3

def product(request,slug):
	product = Product.objects.get(slug=slug)
	context = {
		'product': product
	}
	return render(request, 'catalogo/product.html', context)

product_list = ProductListView.as_view()
category = CategoryListView.as_view()

catalogo/templates/catalogo/_product.html
{% comment %} Apenas para ter maior reutilização de código {% endcomment %}
<div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="{{ produc.get_absolute_url }}">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
            <div class="caption">
                <h3>{{ produc.name }} </h3>
                <p> {{ produc.description }}</p>
                <p><a href="{% url 'checkout:create_cartitem' produc.slug %}" class="btn btn-success" role="button">Add ao carrinho</a> <a href="{{ produc.get_absolute_url }}" class="btn btn-default" role="button">Ver</a></p>
            </div>
        </div>
    </div>

catalogo/templates/catalogo/category.html
{% extends "base.html" %}
{% load pagination %}
{% block title %}
   {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for produc in product_list %}
    {% include "catalogo/_product.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

catalogo/templates/catalogo/product.html
{% extends "base.html" %}

{% block title %}
    {{ product.name }} | {{ block.super }} 
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ product.name }} </h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
      {{ product.description|linebreaks }}
      <br>
      {{ product.price }}
  </div>
</div>
{% endblock %}

catalogo/templates/catalogo/product_list.html
{% extends "base.html" %}
{% load pagination %}
{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for produc in products %}
    {% include "catalogo/_product.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}